version: '3.8'

services:
  operator-client:
    build:
      context: .
      dockerfile: operator-cli/Dockerfile
    container_name: operator-client
    restart: unless-stopped
    volumes:
      - ./keypairs:/app/keypairs
      - ./operators_config.json:/app/operators_config.json
      - ./credentials:/app/credentials
    environment:
      - RUST_LOG=info
      # - RPC_URL=https://api.mainnet-beta.solana.com  # Uncomment to override RPC URL
    # You can override the entrypoint to add additional arguments
    # command: --rpc-url https://api.testnet.solana.com
