/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';

export type OperatorVote = {
  operator: Address;
  slotVoted: bigint;
  voteIndex: number;
  messageLen: number;
  messageData: ReadonlyUint8Array;
};

export type OperatorVoteArgs = {
  operator: Address;
  slotVoted: number | bigint;
  voteIndex: number;
  messageLen: number;
  messageData: ReadonlyUint8Array;
};

export function getOperatorVoteEncoder(): Encoder<OperatorVoteArgs> {
  return getStructEncoder([
    ['operator', getAddressEncoder()],
    ['slotVoted', getU64Encoder()],
    ['voteIndex', getU16Encoder()],
    ['messageLen', getU8Encoder()],
    ['messageData', fixEncoderSize(getBytesEncoder(), 64)],
  ]);
}

export function getOperatorVoteDecoder(): Decoder<OperatorVote> {
  return getStructDecoder([
    ['operator', getAddressDecoder()],
    ['slotVoted', getU64Decoder()],
    ['voteIndex', getU16Decoder()],
    ['messageLen', getU8Decoder()],
    ['messageData', fixDecoderSize(getBytesDecoder(), 64)],
  ]);
}

export function getOperatorVoteCodec(): Codec<OperatorVoteArgs, OperatorVote> {
  return combineCodec(getOperatorVoteEncoder(), getOperatorVoteDecoder());
}
